name: Auto merge main to Live

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 10 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'fakelive'

    - name: Fetch main branch
      run: |
        git fetch origin main:main

    - name: Set up Git
      run: |
        git config user.name "Deland-Han"
        git config user.email "delhan@microsoft.com"

    - name: Merge main to live
      run: |        
        git merge origin/main --allow-unrelated-histories --no-ff -m "Daily automatically push main to live."
        git push origin fakelive

    
